routes/web.php
<?php

use Illuminate\Support\Facades\Mail;


Route::get('/post', function() {
	return view('single');
});


Route::get('/emailtest', function () {

	$data = [
				'title' => 'Email Title',
				'content' => 'lorem ipsum',
			];

	Mail::send('emails.index', $data, function($message){

		$message->to('paulovi91@gmail.com', 'Tibi')->subject('laravel test email');

	});

});



Route::get('404',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);
Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);


Route::get('/', 'PageController@front_page')->name('front-page');
Route::get('/blog', 'PageController@blog')->name('blog');
Route::get('/contact-us', 'PageController@contact_us')->name('contact-us');
Route::get('/about-us', 'PageController@about_us')->name('about-us');
Route::get('/login', 'PageController@login')->name('login');
Route::get('/registration', 'PageController@registration')->name('registration');


Route::group(['middleware' => 'admin'], function(){

	Route::get('/admin', 'AdminUsersController@front_page')->name('admin');
	Route::resource('admin/users', 'AdminUsersController');
	Route::resource('admin/posts', 'AdminPostsController');
	Route::resource('admin/posts-categories', 'AdminCategoriesController');
	Route::resource('admin/posts-tags', 'AdminTagsController');

});
Auth::routes();


/*
Route::namespace('Admin')->as('admin.')->middleware('admin')->group(function() {

	Route::get('/admin', 'AdminPageController@front_page')->name('admin');

});

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin/users', 'AdminUsersController');
*/

resources/views/admin/shared/footer.blade.php
    </div>
    <!-- ./wrapper -->



    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="{{ asset('public/admin/plugins/jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap -->
    <script src="{{ asset('public/admin/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- AdminLTE App -->
    <script src="{{ asset('public/admin/dist/js/adminlte.js') }}"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="{{ asset('public/admin/dist/js/demo.js') }}"></script>



    <!-- PAGE PLUGINS -->

    <!-- InputMask -->
    <script src="{{ asset('public/admin/plugins/input-mask/jquery.inputmask.js') }}"></script>
    <script src="{{ asset('public/admin/plugins/input-mask/jquery.inputmask.date.extensions.js') }}"></script>
    <script src="{{ asset('public/admin/plugins/input-mask/jquery.inputmask.extensions.js') }}"></script>

    <!-- SparkLine -->
    <script src="{{ asset('public/admin/plugins/sparkline/jquery.sparkline.min.js') }}"></script>

    <!-- jVectorMap -->
    <script src="{{ asset('public/admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
    <script src="{{ asset('public/admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>

    <!-- SlimScroll 1.3.0 -->
    <script src="{{ asset('public/admin/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>

    <!-- ChartJS 1.0.2 -->
    <script src="{{ asset('public/admin/plugins/chartjs-old/Chart.min.js') }}"></script>

    <!-- Timepicker -->
    <script src="{{ asset('public/admin/plugins/timepicker/bootstrap-timepicker.min.js') }}"></script>

    <!-- Dropzone -->
    <script src="{{ asset('public/admin/plugins/dropzone/min/dropzone.min.js') }}"></script>



    <!-- PAGE SCRIPTS -->

    <script src="{{ asset('public/admin/dist/js/pages/dashboard2.js') }}"></script>
    <script src="{{ asset('public/admin/admin.js') }}"></script>

  </body>
</html>

resources/views/admin/shared/header.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Laravel Blog Admin</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset('public/admin/plugins/font-awesome/css/font-awesome.min.css') }}">

    <!-- Timepicker -->
    <link rel="stylesheet" href="{{ asset('public/admin/plugins/timepicker/bootstrap-timepicker.min.css') }}">

    <!-- Dropzone -->
    <link rel="stylesheet" href="{{ asset('public/admin/plugins/dropzone/min/basic.min.css') }}">
    <link rel="stylesheet" href="{{ asset('public/admin/plugins/dropzone/min/dropzone.min.css') }}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('public/admin/dist/css/adminlte.min.css') }}">

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- Custom Styles -->
    <link rel="stylesheet" href="{{ asset('public/admin/admin.css') }}" />

  </head>
  <body class="hold-transition sidebar-mini admin @yield('body_class')">
    <div class="wrapper">

      <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
          </li>
        </ul>
      </nav>

resources/views/admin/shared/sidebar.blade.php
<?php 
  $segments = array(); // "" || "categories" || "news"

  for ($i=0; $i <= 10; $i++) {
    if ( Request::segment($i) !== NULL ) {
      $segments []= Request::segment($i);
    }
  }

  $segment = implode('-', $segments);
  //echo '<p class="pull-right">'. $segment .'</p>';
?>


<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
<!-- Brand Logo -->
<a href="#" class="brand-link">
	<img src="{{ asset('public/admin/dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
	  style="opacity: .8">
	<span class="brand-text font-weight-light">AdminLTE 3</span>
</a>

<!-- Sidebar -->
<div class="sidebar">

  <!-- Sidebar Menu -->
  <nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">


      <li class="nav-item">
        <a href="{{ route('front-page') }}" class="nav-link">
          <i class="nav-icon fa fa-home"></i>
          <p>Visit Site</p>
        </a>
      </li>


      <li class="nav-item">
        <a href="{{ route('admin') }}" class="nav-link @if($segment == 'admin') active @endif">
          <i class="nav-icon fa fa-dashboard"></i>
          <p>Dashboard</p>
        </a>
      </li>


      {{-- Media dropdown --}}

      <li class="nav-item has-treeview @if(strpos($segment, 'admin-media') !== false) menu-open @endif">
        <a href="#" class="nav-link">
          <i class="nav-icon fa fa-picture-o"></i>
          <p>Media <i class="fa fa-angle-left right"></i></p>
        </a>
        <ul class="nav nav-treeview">
          <li class="nav-item">
            <a href="#" class="nav-link @if($segment == 'admin-media') active @endif">
              <i class="fa fa-list-ul nav-icon"></i>
              <p>Library</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link nav-link @if($segment == 'admin-media-create') active @endif">
              <i class="fa fa-plus nav-icon"></i>
              <p>Add New</p>
            </a>
          </li>
        </ul>
      </li>


      {{-- Posts dropdown --}}

      <li class="nav-item has-treeview @if(strpos($segment, 'admin-posts') !== false) menu-open @endif">
        <a href="#" class="nav-link">
          <i class="nav-icon fa fa-thumb-tack"></i>
          <p>Posts <i class="fa fa-angle-left right"></i></p>
        </a>
        <ul class="nav nav-treeview">
          <li class="nav-item">
            <a href="{{ route('posts.index') }}" class="nav-link @if($segment == 'admin-posts') active @endif">
              <i class="fa fa-list-ul nav-icon"></i>
              <p>All Posts</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('posts.create') }}" class="nav-link nav-link @if($segment == 'admin-posts-create') active @endif">
              <i class="fa fa-plus nav-icon"></i>
              <p>Add New</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('posts-categories.index') }}" class="nav-link @if(strpos($segment, 'admin-posts-categories') !== false) active @endif">
              <i class="fa fa-list-ul nav-icon"></i>
              <p>Categories</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('posts-tags.index') }}" class="nav-link @if($segment == 'admin-posts-tags') active @endif">
              <i class="fa fa-list-ul nav-icon"></i>
              <p>Tags</p>
            </a>
          </li>
        </ul>
      </li>


      {{-- Users dropdown --}}

      <li class="nav-item has-treeview @if(strpos($segment, 'admin-users') !== false) menu-open @endif">
        <a href="#" class="nav-link">
          <i class="nav-icon fa fa-user"></i>
          <p>Users <i class="fa fa-angle-left right"></i></p>
        </a>
        <ul class="nav nav-treeview">
          <li class="nav-item">
            <a href="{{ route('users.index') }}" class="nav-link @if($segment == 'admin-users') active @endif">
              <i class="fa fa-list-ul nav-icon"></i>
              <p>All Users</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('users.create') }}" class="nav-link @if($segment == 'admin-users-create') active @endif">
              <i class="fa fa-plus nav-icon"></i>
              <p>Add New</p>
            </a>
          </li>
        </ul>
      </li>


    </ul>
  </nav>
  <!-- /.sidebar-menu -->
</div>
<!-- /.sidebar -->
</aside>

resources/views/admin/shared/top_nav.blade.php
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">@yield('page_title')</h1>
      </div>

      <?php /* ?>
      <!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">Dashboard v2</li>
        </ol>
      </div>
      <!-- /.col -->
      <?php */ ?>

    </div>
  </div>
</div>

resources/views/admin/shared/top_page_info.blade.php
@if(Session::has('deleted_user'))
<div class="callout callout-info">
	<p>{{ session('deleted_user') }}</p>
</div>
@endif

@if(Session::has('deleted_user_image'))
<div class="callout callout-danger">
	<p>{{ session('deleted_user_image') }}</p>
</div>
@endif