routes/web.php
<?php

use Illuminate\Support\Facades\Mail;


Route::get('/post', function() {
	return view('single');
});


Route::get('/emailtest', function () {

	$data = [
				'title' => 'Email Title',
				'content' => 'lorem ipsum',
			];

	Mail::send('emails.index', $data, function($message){

		$message->to('paulovi91@gmail.com', 'Tibi')->subject('laravel test email');

	});

});



Route::get('404',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);
Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);


Route::get('/', 'PageController@front_page')->name('front-page');
Route::get('/blog', 'PageController@blog')->name('blog');
Route::get('/contact-us', 'PageController@contact_us')->name('contact-us');
Route::get('/about-us', 'PageController@about_us')->name('about-us');
Route::get('/login', 'PageController@login')->name('login');
Route::get('/registration', 'PageController@registration')->name('registration');


Route::group(['middleware' => 'admin'], function(){

	Route::get('/admin', 'AdminUsersController@front_page')->name('admin');
	Route::resource('admin/users', 'AdminUsersController');
	Route::resource('admin/posts', 'AdminPostsController');
	Route::resource('admin/posts-categories', 'AdminCategoriesController');
	Route::resource('admin/posts-tags', 'AdminTagsController');

});
Auth::routes();


/*
Route::namespace('Admin')->as('admin.')->middleware('admin')->group(function() {

	Route::get('/admin', 'AdminPageController@front_page')->name('admin');

});

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin/users', 'AdminUsersController');
*/

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Post extends Model
{

	protected $fillable = [
							'category_id',
							'tag_id',
							'user_id',
							'attachment_id',
							'title',
							'slug',
							'content',
							'excerpt',
							'status',
							'comment_status',
							'password',
							'date',
							'date_gmt',
						];


    public function user() {
		return $this->belongsTo('App\User');
    }

    public function attachment() {
		return $this->belongsTo('App\Attachment');
    }

    public function categories() {
		return $this->belongsToMany('App\Category', 'categories_posts');
    }

    public function tags() {
		return $this->belongsToMany('App\Tag', 'tags_posts');
    }

}

resources/views/admin/posts/create.blade.php
@extends('admin.layouts.index')

@section('page_title', 'Create Post')
@section('body_class', 'posts-page create')

@section('content')


	{!! Form::open([
					'method' => 'POST', 
					'action' => 'AdminPostsController@store', 
					'class' => 'row',
					'files' => TRUE,
				]) 
	!!}


		<div class="col-md-6">
			<div class="card card-primary">
				<div class="card-body">
					<div class="form-group">
						{!! Form::label('title', 'Title:') !!}
						{!! Form::text('title', null, ['class' => 'form-control']) !!}
					</div>

					<div class="form-group">
						{!! Form::label('slug', 'Slug:') !!}
						{!! Form::text('slug', null, ['class' => 'form-control']) !!}
					</div>

					<div class="form-group">
						{!! Form::label('content', 'Content:') !!}
						{!! Form::textarea('content', null, ['class' => 'form-control']) !!}
					</div>

					<div class="form-group">
						{!! Form::label('excerpt', 'Excerpt:') !!}
						{!! Form::textarea('excerpt', null, ['class' => 'form-control']) !!}
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-6">

			<div class="row">
				<div class="col-md-6">
					<div class="card card-primary">
						<div class="card-header">
							<h3 class="card-title">Categories</h3>
						</div>
						<div class="card-body">
							<div class="form-group">
								@foreach($categories as $c)
									<div class="form-check">
										{{ Form::checkbox('categories[]', $c->id, false, ['class' => 'form-check-input', 'id' => $c->slug]) }}
										<label class="form-check-label" for="{{ $c->slug }}">{{ $c->name }}</label>
									</div>
								@endforeach
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-6">
					<div class="card card-primary">
						<div class="card-header">
							<h3 class="card-title">Tags</h3>
						</div>
						<div class="card-body">
							<div class="form-group">
								@foreach($tags as $t)
									<div class="form-check">
										{{ Form::checkbox('tags[]', $t->id, false, ['class' => 'form-check-input', 'id' => $t->slug]) }}
										<label class="form-check-label" for="{{ $t->slug }}">{{ $t->name }}</label>
									</div>
								@endforeach
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6">
					<div class="card card-primary">
						<div class="card-header">
							<h3 class="card-title">Featured Image</h3>
						</div>
						<div class="card-body">
							<div class="form-group">
								{!! Form::file('attachment_id', ['class' => 'form-control']) !!}
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-6">
					<div class="card card-primary">
						<div class="card-header">
							<h3 class="card-title">Publish</h3>
						</div>
						<div class="card-body">

							<div class="form-group">
								<label>Publish date:</label>
								<div class="input-group">
									<div class="input-group-prepend">
										<span class="input-group-text"><i class="fa fa-calendar"></i></span>
									</div>
									<input type="text" name="publish_day" class="form-control" value="{{ date('Y-m-d') }}" data-inputmask="'alias': 'yyyy-mm-dd'" data-mask="">
									<input type="text" name="publish_time" class="form-control timepicker" value="{{ date('H:i:s') }}">
								</div>
							</div>

						</div>
						<div class="card-footer">
							{!! Form::submit('Publish', ['class' => 'btn btn-primary']) !!}
						</div>
					</div>
				</div>
			</div>

		</div>


	{!! Form::close() !!}


	@include('admin.layouts.form_error')


@endsection

resources/views/admin/posts/edit.blade.php
@extends('admin.layouts.index')

@section('page_title', 'Edit Post')
@section('body_class', 'posts-page edit')

@section('content')


	{!! Form::model($post, [
					'method' => 'PATCH', 
					'action' => ['AdminPostsController@update', $post->id], 
					'class' => 'col-md-6',
					'files' => TRUE,
				]) 
	!!}

		<div class="form-group">
			{!! Form::label('title', 'Title:') !!}
			{!! Form::text('title', null, ['class' => 'form-control']) !!}
		</div>

		<div class="form-group">
			{!! Form::submit('Update post', ['class' => 'btn btn-primary']) !!}
		</div>

	{!! Form::close() !!}


	@include('admin.layouts.form_error')


@endsection

resources/views/admin/posts/index.blade.php
@extends('admin.layouts.index')

@section('page_title', 'Posts')
@section('body_class', 'posts-page index')

@section('content')


<div class="card">
	<div class="card-header hide">
		<h3 class="card-title">Hover Data Table</h3>
	</div>
	<!-- /.card-header -->
	<div class="card-body">
		<div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
			<div class="row">
				<div class="col-sm-12 col-md-6"></div>
				<div class="col-sm-12 col-md-6"></div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
						<thead>
							<tr role="row">
								<th>Title</th>
								<th>Author</th>
								<th>Categories</th>
								<th>Tags</th>
								<th>Featured Image</th>
								<th>Created</th>
							</tr>
						</thead>
						<tbody>

							@if($posts)
								@foreach($posts as $post)
									<tr data-post-id="{{ $post->id }}">
										<td>
											<a href="{{ route('posts.edit', $post->id) }}">{{ $post->title }}</a>
										</td>
										<td>
											<a href="{{ route('users.edit', $post->user->id) }}">{{ $post->user->name }}</a>
										</td>
										<td>
											@if($post->categories)
											<ul>
												@foreach($post->categories as $category)
													<li>{{ $category->name }}</li>
												@endforeach
											</ul>
											@endif
										</td>
										<td>
											@if($post->tags)
											<ul>
												@foreach($post->tags as $tag)
													<li>{{ $tag->name }}</li>
												@endforeach		
											</ul>
											@endif
										</td>
										<td>
											<img src="{{ $post->attachment ? $post->attachment->file : 'https://dummyimage.com/200x200/' }}" alt="" width="100" class="img-responsive img-rounded" />
										</td>
										<td>{{ $post->created_at->format('Y-m-d H:i') }}</td>
									</tr>
								@endforeach
							@endif

						</tbody>
					</table>
				</div>
			</div>

			@if ( $posts->perPage() < $posts->total() )
			<div class="row">
				<div class="col-sm-12 col-md-5">
					<div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to {{ $posts->perPage() }} of {{ $posts->total() }} entries</div>
				</div>
				<div class="col-sm-12 col-md-7">
					<div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate">
						{{ $posts->render() }}
					</div>
				</div>
			</div>
			@endif

		</div>
	</div>
	<!-- /.card-body -->
</div>

@endsection